### ISSUE TITLE
Sponsorships for NodeSchool Phoenix!

### ISSUE THREAD

**Issue by parion** [nodeschool/phoenix#3]
So, we're going to need some companies to sponsor us for NodeSchool Phoenix whether it be location or money for stuff in our budget.

_I will keep updating this list._

I am getting in contact with the following companies about sponsorships:

- 🏢Galvanize: Met them through Chris Huie at Phoenix JavaScript. Offered to show me around a space during the first week of March.

- 🏢Daniel Lovell: Dan has offered to show me around the Mesa Center for Higher Education. Might take up that offer sometime this weekend.

These companies have agreed to sponsor us:

- None yet!

**Comment by maxkorp** [comment]
I've talked very briefly with people at my work, and while we most likely don't have the space to host, they're interested in helping some with costs. As we get more of a feel for what we need (Equipment needs will obviously be determined by whats already available at the hosting space, and the only other things I can think of is maybe food and schwag) I'll let them know and we'll see what we can do.
